### ISSUE TITLE
Add rust targets to README

### ISSUE THREAD

**Issue by CableSynth** [wcampbell0x2a/heretek#40]
When new clone and build you get
```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `scopeguard` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `cfg-if` (lib) due to 1 previous error
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`

error: could not compile `log` (lib) due to 1 previous error
error: could not compile `memchr` (lib) due to 1 previous error
```

Maybe some README additions?

**Comment by CableSynth** [comment]
Or maybe this is a skill issue?????

**Comment by wcampbell0x2a** [comment]
Yes. I build _most_ of my Rust code with musl. Partly for static libc, and partly small and consise libc.

Probably should add something about building this software, this target comes from the `.cargo/config.toml`

**Comment by lukeflo** [comment]
Also run into this error. When changing the target in the `.cargo` file, I receive an error regarding `clap_derive` which in the used version seems unsupported on Linux with glibc. Therefore, a hint in the Readme would be great.

BTW: nice project. I stumbled on it and it helps me understand how to handle external bg processes with Rust while capturing the output etc. Thanks.

**Comment by CableSynth** [comment]
Change from Readme/documentation to remove target? @wcampbell0x2a
